# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKWQVynhSiGIuiL_XOvC88y7hJP6oInG
"""

import pickle
import pandas as pd
from fastapi import FastAPI, UploadFile, File
from fastapi.responses import StreamingResponse
import io

model = pickle.load(open("final_logistic_model_UPDATED.pkl", "rb"))
scaler = pickle.load(open("scaler_uPDATED.pkl", "rb"))

app = FastAPI()

@app.post("/score_csv")
async def score_csv(file: UploadFile = File(...)):
    df = pd.read_csv(file.file)

    X = df.drop(columns=["PaymentMiss_30Days"], errors="ignore")
    X_scaled = scaler.transform(X)

    df["Default_Probability"] = model.predict_proba(X_scaled)[:, 1]

    df["Risk_Bucket"] = df["Default_Probability"].apply(
        lambda p: "High" if p >= 0.7 else "Medium" if p >= 0.4 else "Low"
    )

    output = io.StringIO()
    df.to_csv(output, index=False)
    output.seek(0)

    return StreamingResponse(output, media_type="text/csv")
